version: "3.8"
services:
  web:
    build: .
    container_name: flask_web
    environment:
      - docker=true
    restart: always
    ports:
      - "31337:1337"
    networks:
      - explorer-net
    depends_on:
      - psql
      - redis

  psql:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    expose:
      - 5432
    restart: always
    networks:
      - explorer-net

  redis:
    image: redis
    expose:
      - 6379
    restart: always
    networks:
      - explorer-net
networks:
  explorer-net:
    driver: bridge

volumes:
  postgres_data:
